name: Dump env
on: 
  push:
  workflow_dispatch:
  
jobs:
  Dump_context:
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      run:   echo "$GITHUB_CONTEXT"
      shell: bash
      env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
